### ISSUE TITLE
merging of different timeseries?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#13]
I don't understand https://github.com/raintank/graphite-raintank/commit/0d2534960a25bd3078967b93e46daa0f979ee203
specifically this part:

```
        logger.debug('fetch_from_tank', url=url, status_code=resp.status_code, body=resp.text)
        dataMap = {}
        for result in resp.json():
            path = pathMap[result['Target']]
            if path in dataMap:
                #we need to merge the datapoints.
                dataMap[path].extend(result['Datapoints'])
                # sort by timestamp
                dataMap[path].sort(key=lambda x: x[1])
            else:
                dataMap[path] = result['Datapoints']
        return dataMap
```

if 2 series are returned with the same name but different points, should we really create 1 series that is basically both series appended to each other?

**Comment by woodsaj** [comment]
Yes.  This happens when an endpoint is deleted and new one created with the same name.  So the series name is the same, but the metric ID is different (because there is an endpoint_id tag).  So though there are two series, there is no overlap in datapoints.

**Comment by Dieterbe** [comment]
right, makes sense. and it's ok for there to be a gap in between the two series? i guess that's also taken care of by the null-filling logic in https://github.com/raintank/graphite-raintank/blob/master/graphite_raintank.py#L196-L238

**Comment by woodsaj** [comment]
While we have plans to remove the endpoint_id from the metric tags, and instead use the endpoint name or slug, we also want to add the "interval" to be part of the metric.Id, so that changes in the metric interval result in a new series being created.  When querying, we would still need to handle the scenario of there being more then 1 metricIndex result for a specific series name.
