### ISSUE TITLE
graphite-raintank doesn't always query NMT

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#2]
not sure yet what's going on.
but so we run 6 benchmarks
https://github.com/raintank/raintank-tsdb-benchmark/blob/master/run.sh#L68-L75
(min diversity means query same target over and over, max diversity means select random targets from the set of all known targets)

in one particular test run, it looked like graphite-raintank was only querying NMT in all 3 max diversity cases, but not in the 3 min diversity cases.

and now a run just completed where it was only querying NMT for the `"max-diversity" 1h 180s 100` test (third last), and the last one, `"max-diversity" 24h 180s 100` but not the first max-diversity.

note the background load, created by graphite-watcher of 10 requests/s which is occassionally visible (but during a chunk in the middle it had crashed and is invisible).
also green is hidden by yellow, but luckily yellow is enough to see what's going on.
![huh2](https://cloud.githubusercontent.com/assets/20774/10718942/6062e06e-7b54-11e5-817d-2d829d1552ca.png)
![huh](https://cloud.githubusercontent.com/assets/20774/10718924/f2c4739c-7b53-11e5-8ac8-c8fd59e00bee.png)

**Comment by Dieterbe** [comment]
the NMT dashboard confirms this
![huh3](https://cloud.githubusercontent.com/assets/20774/10718967/9a33d06e-7b54-11e5-8669-f1bcc318512a.png)

**Comment by Dieterbe** [comment]
now also with snapshots!
https://snapshot.raintank.io/dashboard/snapshot/yxlxziKkFxL8ArH1mxeUW3ynKNKpel1q
https://snapshot.raintank.io/dashboard/snapshot/MP4Vf7nOiwI32JVOlEmuipJGi2oVKJmr

**Comment by woodsaj** [comment]
These comments dont make any sense to me.  Can you try explaining what the problem you are seeing is.  Specifically explaining how you think these graphs show the problem.

**Comment by Dieterbe** [comment]
ok let's focus just on the 2nd graph screenshot.
the 2nd graph screenshot is the one on which the 6 short benchmark run periods are most clearly visible. the yellow lines on it show that only benchmark run 4 and 6 are causing traffic to NMT. (the other yellow lines that are lower are caused by some "background load" from graphite-watcher, not the actual benchmark runs).
the 6 benchmarks are run via https://github.com/raintank/raintank-tsdb-benchmark/blob/master/run.sh, the last arguments are the rates. i.e. first two are at 200 rps and the last 4 at 100 rps. the light blue (search ES) is the only series that corresponds to this rate of data requests, the yellow is way too low.

**Comment by woodsaj** [comment]
I am unable to replicate your problem in my stack (which is the latest raintank-docker#tank)

I did drop down the request rate from 200 down to 50, as my desktop can't handle the load.  But the 6 benchmark tests all generated the expected ops/s for es search, query Tank, unmarshal

![image](https://cloud.githubusercontent.com/assets/8415072/10762004/034bed1a-7cff-11e5-82d2-6ef609bf8bac.png)

**Comment by Dieterbe** [comment]
nice! i'll have to dive deeper on my stack and figure out what's up
