### ISSUE TITLE
proposal: move this into metric-tank repository

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#24]
in my mind it makes sense to maintain both together in one place. so that if we need to changes to both (for example a schema change) we can do that in 1 commit. doing changes and tracking version compatibility between two repos is annoying. it's also more simple to find that way.

**Comment by Dieterbe** [comment]
@woodsaj ?

**Comment by woodsaj** [comment]
I am ok with moving the code around. But i really think that we need to move both raintank-metric/metric-tank and graphite-raintank into a new repo.

**Comment by Dieterbe** [comment]
In the above ticket you said

> I dont think that graphite-raintank and metric-tank should be in the same repo. The majority of the time these two pieces of software will be modified independently of each other.

so i'm just going to reluctantly close this.
