### ISSUE TITLE
ES is almost the most cpu intensive part of our stack, without any events workload, just querying graphite-api

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#3]
as you can see from the cpu usage graphs on https://snapshot.raintank.io/dashboard/snapshot/yxlxziKkFxL8ArH1mxeUW3ynKNKpel1q, there's 6 short benchmark runs that are querying graphite-api for metrics data.  there is no direct ES related workload like events.

only the 3rd last and last are actually querying NMT, not that it matters much.
i was surprised that ES consumes so much cpu. granted graphite-api has 16 processes each at around 20, so totalling 320, but still. (note only 1 of the graphite processes is shown, otherwise the snapshot upload timed out)

this is using graphite-raintank btw, not our graphite-kairosdb or graphite-cassandra we're using in dev/prod.

**Comment by Dieterbe** [comment]
btw sorry filed this under the wrong repo.. not that we have any other particular repo that is particularly fitting (ops comes close but this doesn't require any secrecy)

**Comment by woodsaj** [comment]
This should/will be addressed by https://github.com/raintank/raintank-metric/issues/32

**Comment by Dieterbe** [comment]
reran the benchmarks again. looks like ES cpu went down by about 3x. 
this is without NMT aggregation, if NMT aggregates, it's the largest cpu consumer.
so ES is still pretty high but not to such an extent that it annoys me enough to keep this ticket open.
now graphite-python is the largest cpu consumer, wihch is more acceptable :)
![es-cpu](https://cloud.githubusercontent.com/assets/20774/11676817/852deb9a-9e9b-11e5-9c76-ecd4292f03e5.png)
