### ISSUE TITLE
increase default series limit

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#32]
https://github.com/raintank/graphite-metrictank/commit/9c5b64725b3965c63586c7d2d7980b5ae9365daa was good, but perhaps 500 is too strict of a default value.  Especially for people doing benchmarks.
At which point does a large number of series _really_ become a problem?   Metrictank itself already has safeguards to block requests it can't handle, so graphite-metrictank can be pretty lax about it and only block what looks like ridiculous requests.
Let's say we cap at 10k series and some rough back of the envelope math:
Assuming the json doc for each metricdef is 300B, that's 3MB of data. that's still a not-terrible amount to pull in over a lan network (between graphite-api and ES). python's internal datastructures are pretty RAM hungry so maybe 100MB in RAM, which seems fine too.
and if the id's are 50B each, that's 500kB of a request from graphite-api to metrictank which is also fine. won't be fast, but that's the user's problem.

so how about default series limit of 10000 ?
@woodsaj @nopzor1200 @obfuscurity

**Comment by obfuscurity** [comment]
I think 1000 should be plenty in most circumstances.

Long-term I think some sort of pagination would make more sense. Possibly scenario: user requests wildcard metric; backend find `results > 1000` and returns an HTTP 206 with the first paginated set of results. It would require coordination on both ends but I know there's precedence out there for this.

**Comment by woodsaj** [comment]
I am ok with 10k. 

As handling pagination requires changes to Grafana, there is no point in graphite-metrictank attempting the feature until it is supported in graphite-web.  So realistically, this wont be a feature until graphite-ng.
