### ISSUE TITLE
needs to pass any consolidateBy, maxDataPoints options received to metric_tank

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#9]
when graphite gets a request with these options set, they need to be passed to metric_tank.

**Comment by Dieterbe** [comment]
ugh, consolidateBy is a function in graphite, not a parameter.
so graphite could get `target=consolidateBy(Sales.widgets.largeBlue, 'sum')` or even `target=consolidateBy(some(other(functions(Sales.widgets.largeBlue)), 'sum')`
it seems very unlikely that we're able to get this information inside the finder, but i'll keep looking.
also if it wraps other functions it's gonna be very hard to do the right thing.

maybe we could basically just ignore consolidateBy in graphite-raintank & metric-tank and just apply the function based on the metric metadata, should work in most cases, except when people want a very specific behavior, then we would do the wrong thing :(

also not sure about maxDataPoints yet.  in graphite's app.py it looks like that's only used in the json output, and is not passed on to the code responsible for getting the series, but TimeSeries in datalib does have a clause on consolidateBy so there's some hope.

**Comment by Dieterbe** [comment]
hmm it looks like consolidateBy() sets the consolidationFunc on the series, so the nesting may be irrelevant and all hope is not lost.  i'm looking more into it.

**Comment by woodsaj** [comment]
There is a really easy way to pass information around in a Flask App.  just use `flask.g`

flask.g is a global variable that can be accessed anywhere within the same request. This is what we use for setting the OrgId after authenticating a request.
https://github.com/raintank/graphite-api/blob/master/graphite_api/app.py#L76

So you can do the same for MaxDataPoints just after https://github.com/raintank/graphite-api/blob/master/graphite_api/app.py#L309

consolidateBy can probably be done similarly.

**Comment by Dieterbe** [comment]
maxDataPoints was easy.
consolidateBy is going to be trickier, as it is per-target, not per request. (i.e. you can plot 2 series that need consolidation via different functions). the best i can come up with is using the same syntax in metric-tank, i.e. requesting `consolidateBy(<target>,<func>)` and parsing that out.

**Comment by woodsaj** [comment]
https://github.com/raintank/graphite-api/pull/6

tested this with queries like`diffSeries(alias(summarize(consolidateBy(litmus.google_com.dev1.ping.max, 'max'), '5min', 'avg', false), 'max'), alias(summarize(consolidateBy(litmus.google_com.dev1.ping.min, 'min'), '5min', 'avg', false), 'min'))`

**Comment by Dieterbe** [comment]
the irony is that in standard graphite the site admin can configure 1 rollup function per series (for whisper) , and graphite will automatically read from the best fitting archive (rolled up using said predefined function), and then consolidate with the function provided by the user (consolidateBy) while generating the response, so your data can easily become nonsense. choosing both rollup-method and runtime-consolidation using the same function seems much better.  but if we wanted to be "just as good" as graphite, metric-tank could just infer the aggregation to apply based on the metric type to bring down the amount of points, ignoring consolidateBy and then graphite-api could do the "final consolidation touch" using consolidateBy, similar to how it works for whisper. but clearly we can do better.

**Comment by Dieterbe** [comment]
using https://github.com/raintank/graphite-raintank/pull/10 + https://github.com/raintank/graphite-api/pull/7 makes it work for me:
bottom screen is target strings and maxDataPoints coming into metric-tank.
![consolidateby](https://cloud.githubusercontent.com/assets/20774/11639027/1075799c-9d8f-11e5-99c2-17e9ff96fd7b.png)

**Comment by Dieterbe** [comment]
both PR's merged :+1:
